// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyjbgaaypvylbtehcars.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5amJnYWF5cHZ5bGJ0ZWhjYXJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTUxMTYsImV4cCI6MjA2OTczMTExNn0.Sj6sAY1c5HxLN6QJEB6c1uTKv73MXZ54fg8IsXEMPSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});